name: Publish Docs Action
description: Upload new revisions of division documents
author: olillin

branding:
  icon: 'file-plus'
  color: blue

inputs:
  path:
    description: Path to the file to upload
    required: true
  base_url:
    description: The docs server to publish documents to
    required: false
    default: 'https://newdocs.olillin.com'
  category_slug:
    description: Slug of the category where the document resides
    required: true
  document_slug:
    description: Slug of the document to update
    required: true
  revised_at:
    description: Date when the document was revised
  ignore_conflicts:
    description: Ignore conflicts with existing revisions

outputs:
  location:
    description: URL which points to the published revision

runs:
  using: node24
  main: dist/index.js
