name: Publish Docs Action
description: Upload new revisions of division documents
author: olillin

branding:
  icon: 'file-plus'
  color: blue

inputs:
  category-stub:
    description: Stub of the category where the document resides
    required: true
  document-stub:
    description: Stub of the document to update
    required: true
  revised-at:
    description: Date when the document was revised

outputs:
  location:
    description: URL which points to the published revision

runs:
  using: node24
  main: dist/index.js
